### ISSUE TITLE
When to use SplitCap and what its relationship with CATE?

### ISSUE THREAD

**Issue by yuwvandy** [ViktorAxelsen/TFE-GNN#8]
Thank you for the great work.

I just downloaded the dataset and after that, I want to check whether my following procedure is correct:
(1) Use SplitCap to split traffic into more fine-grained level
(2) Filter out those non-TCP ones.
(3) run pcap2npy.py to convert

If the above procedure is correct, what is the reason for only keeping TCP one?

**Comment by ViktorAxelsen** [comment]
We first use SplitCap to obtain the bidirectional flows after downloading the dataset. Then, filter out those non-TCP ones. Next, the data files are divided into different categories based on the description provided in the CATE folder. Finally, run the pcap2npy.py.

**Comment by ViktorAxelsen** [comment]
We first use SplitCap to obtain the bidirectional flows after downloading the dataset. Then, filter out those non-TCP ones. Next, the data files are divided into different categories based on the description provided in the CATE folder. Finally, run the pcap2npy.py.

Although the official website of the dataset describes each data category, it does not provide a standard data partition method. So, we categorize the data ourselves according to the description of the data categories on the official website. The CATE folder provides our categorization details.

Since UDP is a non-persistent connection, the number of UDP files obtained through SplitCap is very large, and most UDP files only contain a very small number of packets. What's more, a considerable part of these packets do not contain the payload (TFE-GNN requires both header and payload to construct graphs). Therefore, considering the training overhead and the feasibility of UDP as a training sample for TFE-GNN, we only consider TCP files in this work.

**Comment by yuwvandy** [comment]
> We first use SplitCap to obtain the bidirectional flows after downloading the dataset. Then, filter out those non-TCP ones. Next, the data files are divided into different categories based on the description provided in the CATE folder. Finally, run the pcap2npy.py.
> 
> Although the official website of the dataset describes each data category, it does not provide a standard data partition method. So, we categorize the data ourselves according to the description of the data categories on the official website. The CATE folder provides our categorization details.
> 
> Since UDP is a non-persistent connection, the number of UDP files obtained through SplitCap is very large, and most UDP files only contain a very small number of packets. What's more, a considerable part of these packets do not contain the payload (TFE-GNN requires both header and payload to construct graphs). Therefore, considering the training overhead and the feasibility of UDP as a training sample for TFE-GNN, we only consider TCP files in this work.

Thank you for the prompt and detailed reply!
